### ISSUE TITLE
Issue on existing server and creating new world..

### ISSUE THREAD

**Issue by BuckitHead** [rwtema/DenseOres#114]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.1.jar)
  thaumicinfusion (ThaumicInfusion-1.8.9-4.82.jar)
  FMLPlugin (InventoryTweaks-1.60-beta-39.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.6.4.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  BetterFoliageLoader (BetterFoliage-MC1.8.x-2.0.4.jar)
  EnderCorePlugin (EnderCore-1.8.9-0.3.0.9-beta.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 3/13/16 5:51 AM
Description: Exception while updating neighbours

java.lang.NoClassDefFoundError: com/rwtema/denseores/modelbuilder/ModelBuilder
	at com.rwtema.denseores.client.DynamicBlockModel.handleState(DynamicBlockModel.java:62)
	at com.rwtema.denseores.blocks.BlockDenseOre.func_176221_a(BlockDenseOre.java:309)
	at net.minecraft.block.Block.isSideSolid(Block.java:1105)
	at net.minecraft.world.World.func_175683_a(World.java:2393)
	at net.minecraft.block.BlockRailBase.func_176204_a(BlockRailBase.java:106)
	at net.minecraft.world.World.func_180496_d(World.java:505)
	at net.minecraft.world.World.func_175685_c(World.java:454)
	at net.minecraft.world.World.func_175722_b(World.java:409)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:354)
	at net.minecraft.world.World.func_180501_a(World.java:335)
	at net.minecraft.world.World.func_175656_a(World.java:394)
	at com.rwtema.denseores.WorldGenOres.overrideChunkBlock(WorldGenOres.java:28)
	at com.rwtema.denseores.blockstates.OreType$2.generate(OreType.java:230)
	at com.rwtema.denseores.WorldGenOres.genChunk(WorldGenOres.java:78)
	at com.rwtema.denseores.WorldGenOres.generate(WorldGenOres.java:64)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:262)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1081)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:114)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:307)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:109)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:123)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.rwtema.denseores.modelbuilder.ModelBuilder
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 26 more
Caused by: java.lang.NullPointerException

**Comment by bushbaby1234** [comment]
similar issue here
http://pastebin.com/skRhRDuv

**Comment by Thorton101** [comment]
hello,
updated to the latest version of DenseOre and entering an existing world results in a crash:
[http://pastebin.com/bGT4KyAe]
same version startet a new world:
[http://pastebin.com/TTZxvwCy]

best regards
Thorton

**Comment by PNDAgent117** [comment]
Same Issue as well, with only dense ores installed.
[http://pastebin.com/m6mj3s2j]

**Comment by BuckitHead** [comment]
Still happening with latest version....

**Comment by Thorton101** [comment]
hello,

crash still happening with version 'Dense Ores alpha 2.0.2'.
Disabling the mod an world creation is possible, but it deletes fluid.electrum from
Tinkers Construct.

best regards
Thorton
