### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by Leon1236** [rwtema/DenseOres#118]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.60-beta-39.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  CoreXU2 (extrautils2-1.8.9-alpha--0.0.0.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.3.jar)
  CoreMod (Aroma1997Core-1.8.9-1.0.4.1.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 16.03.16. 12:16
Description: Exception while updating neighbours

java.lang.NoClassDefFoundError: com/rwtema/denseores/modelbuilder/ModelBuilder
	at com.rwtema.denseores.client.DynamicBlockModel.handleState(DynamicBlockModel.java:61)
	at com.rwtema.denseores.ProxyClient.loadModel(ProxyClient.java:26)
	at com.rwtema.denseores.blocks.BlockDenseOre.func_176221_a(BlockDenseOre.java:310)
	at net.minecraft.block.Block.isSideSolid(Block.java:1105)
	at thaumcraft.common.lib.utils.BlockUtils.isBlockTouching(BlockUtils.java:355)
	at thaumcraft.common.blocks.world.ore.BlockCrystal.func_176204_a(BlockCrystal.java:162)
	at net.minecraft.world.World.func_180496_d(World.java:505)
	at net.minecraft.world.World.func_175685_c(World.java:454)
	at net.minecraft.world.World.func_175722_b(World.java:409)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:354)
	at net.minecraft.world.World.func_180501_a(World.java:335)
	at net.minecraft.world.World.func_175656_a(World.java:394)
	at com.rwtema.denseores.WorldGenOres.overrideChunkBlock(WorldGenOres.java:28)
	at com.rwtema.denseores.blockstates.OreType$2.generate(OreType.java:230)
	at com.rwtema.denseores.WorldGenOres.genChunk(WorldGenOres.java:78)
	at com.rwtema.denseores.WorldGenOres.generate(WorldGenOres.java:64)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:262)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1081)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:114)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:307)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:109)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:123)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.rwtema.denseores.modelbuilder.ModelBuilder
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.rwtema.denseores.client.DynamicBlockModel.handleState(DynamicBlockModel.java:61)
	at com.rwtema.denseores.ProxyClient.loadModel(ProxyClient.java:26)
	at com.rwtema.denseores.blocks.BlockDenseOre.func_176221_a(BlockDenseOre.java:310)
	at net.minecraft.block.Block.isSideSolid(Block.java:1105)
	at thaumcraft.common.lib.utils.BlockUtils.isBlockTouching(BlockUtils.java:355)
	at thaumcraft.common.blocks.world.ore.BlockCrystal.func_176204_a(BlockCrystal.java:162)

-- Block being updated --
Details:
	Source block type: ID #814 (tile.null // com.rwtema.denseores.blocks.BlockDenseOre)
	Block: thaumcraft:crystal_aqua[gen=1,size=3]
	Block location: World: (132,13,167), Chunk: (at 4,0,7 in 8,10; contains blocks 128,0,160 to 143,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.world.World.func_180496_d(World.java:505)
	at net.minecraft.world.World.func_175685_c(World.java:454)
	at net.minecraft.world.World.func_175722_b(World.java:409)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:354)
	at net.minecraft.world.World.func_180501_a(World.java:335)
	at net.minecraft.world.World.func_175656_a(World.java:394)
	at com.rwtema.denseores.WorldGenOres.overrideChunkBlock(WorldGenOres.java:28)
	at com.rwtema.denseores.blockstates.OreType$2.generate(OreType.java:230)
	at com.rwtema.denseores.WorldGenOres.genChunk(WorldGenOres.java:78)
	at com.rwtema.denseores.WorldGenOres.generate(WorldGenOres.java:64)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:262)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1081)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:114)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:307)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:109)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:123)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 979864592 bytes (934 MB) / 2269118464 bytes (2164 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4608m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.1764 41 mods loaded, 41 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1764.jar) 
	UCHIJAA	Forge{11.15.1.1764} [Minecraft Forge] (forge-1.8.9-11.15.1.1764.jar) 
	UCHIJAA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.8.9-1.0.4.1.jar) 
	UCHIJAA	CoreXU2{1} [CoreXU2] (minecraft.jar) 
	UCHIJAA	Aroma1997CoreHelper{1.0.4.1} [Aroma1997Core|Helper] (Aroma1997Core-1.8.9-1.0.4.1.jar) 
	UCHIJAA	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.8.9-1.1.2.0.jar) 
	UCHIJAA	AromaBackup{0.0.1.1.b26} [AromaBackup] (AromaBackup-1.8.9-0.0.1.1.b26.jar) 
	UCHIJAA	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.8.9-0.0.1.1.b26.jar) 
	UCHIJAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.8.9-alpha--0.0.0.jar) 
	UCHIJAA	JEI{2.28.7.174} [Just Enough Items] (jei_1.8.9-2.28.7.174.jar) 
	UCHIJAA	BloodMagic{1.8.9-2.0.0-19} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-19.jar) 
	UCHIJAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJAA	Thaumcraft{5.2.3} [Thaumcraft] (Thaumcraft-1.8.9-5.2.3.jar) 
	UCHIJAA	Botania{r1.8-299} [Botania] (Botania-unofficial.r1.8-299.jar) 
	UCHIJAA	Chameleon{1.8.9-0.2.1} [Chameleon] (Chameleon-1.8.9-0.2.1.jar) 
	UCHIJAA	chiselsandbits{mc1.8.9-v1.8.11} [Chisels & Bits] (chiselsandbits-mc1.8.9-v1.8.11.jar) 
	UCHIJAA	ComputerCraft{1.78} [ComputerCraft] (ComputerCraft1.78.jar) 
	UCHIJAA	ElecCore{1.4.247} [ElecCore] (ElecCore-1.8.9-1.4.247.jar) 
	UCHIJAA	deepresonance{1.1.4beta17} [DeepResonance] (deepresonance-1.8.9-1.1.4beta17.jar) 
	UCHIJAA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UCHIJAA	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UCHIJAA	FTBL{2.0.2} [FTBLib] (FTBLib-1.8.9-2.0.2.jar) 
	UCHIJAA	FTBU{2.0.2} [FTBUtilities] (FTBUtilities-1.8.9-2.0.2.jar) 
	UCHIJAA	inventorytweaks{1.60-beta-39-eae6253} [Inventory Tweaks] (InventoryTweaks-1.60-beta-39.jar) 
	UCHIJAA	IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
	UCHIJAA	JEIAddons{0.12.0.57} [Just Enough Items Addons] (JEIAddons_1.8.9-0.12.0.57.jar) 
	UCHIJAA	journeymap{1.8.9-5.1.5} [JourneyMap] (journeymap-1.8.9-5.1.5-unlimited.jar) 
	UCHIJAA	jeresources{0.4.0} [Just Enough Resources] (JustEnoughResources-1.8.9-0.4.0.jar) 
	UCHIJAA	mantle{1.8.9-0.9.0.jenkins97} [Mantle] (Mantle-1.8.9-0.9.0.jar) 
	UCHIJAA	Psi{beta-23} [Psi] (Psi-beta-23.jar) 
	UCHIJAA	quantumflux{2.0.1} [QuantumFlux] (quantumflux-1.8.9-2.0.1.jar) 
	UCHIJAA	rftools{4.23beta32} [RFTools] (rftools-1.8.9-4.23beta32.jar) 
	UCHIJAA	rftoolsdim{4.22beta28} [RFTools Dimensions] (rftoolsdim-1.8.9-4.22beta28.jar) 
	UCHIJAA	SoulShardsTOW{1.8.9-2.2.7-14} [Soul Shards - The Old Ways] (SoulShards-TOW-1.8.9-2.2.7-14.jar) 
	UCHIJAA	StorageDrawers{1.8.9-2.4.4} [Storage Drawers] (StorageDrawers-1.8.9-2.4.4.jar) 
	UCHIJAA	tconstruct{1.8.9-2.1.0.jenkins101} [Tinkers' Construct] (TConstruct-1.8.9-2.1.0.jar) 
	UCHIJAA	tknowledge{0.2.0} [Thaumaturgical Knowledge] (Thaumaturgical Knowledge-0.2.1 - 1.8.9.jar) 
	UCHIJAA	warpbook{2.0.42} [Warp Book] (warpbook-1.8.9_2.0.42.jar) 
	UCHIJAA	wawla{1.4.7} [What Are We Looking At] (Wawla-1.4.7-1.8+.jar) 
	UCHIJAA	denseores{1.0} [denseores] (denseores-1.8-alpha-2.0.2.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.60-beta-39.jar)
  invtweaks.forge.asm.ContainerTransformer
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
CoreXU2 (extrautils2-1.8.9-alpha--0.0.0.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.3.jar)
  
CoreMod (Aroma1997Core-1.8.9-1.0.4.1.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- TinkerDebug (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by BraynStorm** [comment]
[Crash report](http://pastebin.com/uYNz0TnM)
`Forge: 11.15.1.1764`
`DenseOres 2.0.2 Alpha (same thing with 2.0.1 BTW)`

**Comment by Darkosto** [comment]
I seem to be getting the same issue: http://pastebin.com/D8VfcBjf

Forge 1764 and Dense Ores 2.0.2

**Comment by JinxsoMC** [comment]
Error does not occur on Forge 11.15.1.1757 for me.

**Comment by SouthApple** [comment]
Same issue here on Forge 1757 with Dense Ores 2.0.2, had the same issue with 2.0.1. 
http://pastebin.com/XDf4DnwX

Retried using 1764, got the same thing: http://pastebin.com/nHtQtGni

Seems to be an issue with Thaumcraft crystals from what I can tell.

**Comment by Darkosto** [comment]
I'm not using thaumcraft in my pack, so that shouldn't be it.

**Comment by benten2000** [comment]
Been trying both v2.0.2 and 2.0.1 on its own with no other mods and it crashes everytime with the ModelBuilder error when entering a created world. Used both the recommended forge to the latest but nothing helped.

**Comment by JetstormLP** [comment]
Same issue here. Crash on world load from an issue with the model builder. http://pastebin.com/BTRhmYm7

**Comment by utoxin** [comment]
Same error on my custom pack. http://pastebin.com/p16uVAkx
