### ISSUE TITLE
[Dense Ores 1.6.1] Crash on loading

### ISSUE THREAD

**Issue by pkuyken** [rwtema/DenseOres#77]
I crash on loading with the following crash log: http://paste.ee/p/AsQPd

The relevant lines seem to be:

Caused by: java.lang.NoClassDefFoundError: ic2/api/recipe/IRecipeInput
	at com.rwtema.denseores.modintegration.ModIntegration.<clinit>(ModIntegration.java:19)
	at com.rwtema.denseores.DenseOresMod.init(DenseOresMod.java:37)

I do not have IC2 installed.

**Comment by Sailren** [comment]
same crash here

**Comment by ElvenChaos** [comment]
It looks like 1.6.1 didn't fix the problem D: http://pastebin.com/GsYxPcrg

**Comment by ate0ate** [comment]
Yup. Same thing here. No IC2 or IC2 API, but I still crash.

**Comment by greenrhino33** [comment]
Same issue here. http://pastebin.com/uhPg3kuZ No IC2 installed.

**Comment by SanAndreasP** [comment]
I have to report this as well: https://gist.github.com/SanAndreasP/4c7bbebb6ec03e480a78
